### ISSUE TITLE
No support for white spaces in project directory

### ISSUE THREAD

**Issue by NicolasRiou** [ModernRonin/ProjectRenamer#16]
Hello and thank you for this tool, I love it. 

I did encounter a problem with a dotnet list command though, because there was white space in a folder name. I could workaround the issue by moving my project to a temp folder without white space in its name. 

![image](https://user-images.githubusercontent.com/4700137/101630572-5c325180-3a23-11eb-97b0-08665621c607.png)

Hope this helps.

**Comment by ModernRonin** [comment]
Hi Nicolas,
thanks for letting me know, I'll try and look into it before the weekend.

Cheers,
MR
